### PR TITLE
Update failing tests

### PR DESCRIPTION
**Pull request by fmdkdd**
I was looking at the tests failures reported in #1163, and managed to fix a few of them.

The rust failures were introduced by #1182.  I did not run the tests locally, and somehow it passed through our CI.

The haskell failures are due to small changes in GHC output.  There are now dots in the output:
```
Error.hs:4:16: error:
    • Couldn't match type ‘Bool’ with ‘[Char]’
      Expected type: String
        Actual type: Bool
    • In the first argument of ‘putStrLn’, namely ‘True’
      In the expression: putStrLn True
      In an equation for ‘foo’: foo = putStrLn True
```
I've added them to the tests as-is, but we could also trim them from the output.  Maybe @flycheck/haskell has an opinion on that.

The typescript failure was due to a deprecated rule, the same issue as #1174.

### CODE REVIEW

**Comment by purcell** [comment]
Ideally the Haskell patterns would match both the old and new output formats, since people will continue to use the older GHC (7.8, 7.10?) for quite some time, and Flycheck should support it. Is that the case here?

**Comment by fmdkdd** [comment]
@purcell That's a good point.  The changes I've made to the error-parser are backwards-compatible, since I've only added an `optional` rx matcher for catching error IDs.

But the test output will definitely fail with previous versions of GHC.  So users won't be affected, unless they try to run the integration tests with an older GHC.

From what I gather, Flycheck makes no guarantees for backward-compatibility.  If a checker fails after updating Flycheck, we even suggest to update the external tools to a newer version.

Our integration tests are especially version-specific, since the slightest change in compiler output will make them fail.  We don't have any infrastructure in place to handle tests for multiple tool versions.  Should we?  I might open an issue if I don't find the answer clearly stated anywhere.

**Comment by fmdkdd** [comment]
Thanks to flycheck/flycheck-rust#48, I noticed there is a plural form of the useless Rust error message "aborting due to previous error".  I've updated the regexp of that commit to catch these as well.

**Comment by purcell** [comment]
> Our integration tests are especially version-specific, since the slightest change in compiler output will make them fail. We don't have any infrastructure in place to handle tests for multiple tool versions. Should we? I might open an issue if I don't find the answer clearly stated anywhere.

No, I wouldn't personally introduce that just for this case, but we should still do what we can to keep patterns backwards-compatible where it makes sense for core language machinery (e.g. major compiler versions). For pure add-on tools like `eslint`, it's less of a concern: people who use the latest flycheck will also want the latest eslint.

**Comment by fmdkdd** [comment]
> we should still do what we can to keep patterns backwards-compatible where it makes sense

Agreed.  And *if* we had tests for major versions, they would help maintaining backward-compatibility.  That's what I'm proposing in #1190.

**Comment by cpitclaudel** [comment]
Thanks! This all looks good. I replied on the separate thread.
